export const metadata = {
  title: "QuackGPT",
  description: "Generated by QuackGPT.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
